### ISSUE TITLE
Change text label of a "Process" button for resolved issue

### ISSUE THREAD

**Issue by rapee** [youpin-city/youpin-web-admin#104]
In a modal for resolved issue, there're
- Archive button
- Process button

Consider changing label from "Process" to something easier to guess e.g. "Send to Process", "Make Reprocess".

Is "Archive" good enough?

**Comment by puripant** [comment]
"Archive" should be okay.

According to the built-in Mac dictionary, the synonyms of "Process" are "deal with, attend to, see to, sort out, handle, take care of, action." "Process" seems to be the best option. Maybe "Reprocess" for resolved issues
