### ISSUE TITLE
[UI][BMA] Swap เรื่องร้องเรียน with Dashboard on the left sidebar

### ISSUE THREAD

**Issue by thitiluang** [youpin-city/youpin-web-admin#148]
From the observation, users tend to use **เรื่องร้องเรียน** page as the main function. So let's set this one as default screen. **Dashboard** is not that powerful and useful for now. @rapee 
<img width="209" alt="screen shot 2560-09-29 at 11 00 49 am" src="https://user-images.githubusercontent.com/32285960/31000691-e3be8d58-a507-11e7-8526-ee7ae79b4b1d.png">

**Comment by laikhram** [comment]
Done
