### ISSUE TITLE
Archive pin

### ISSUE THREAD

**Issue by supasate** [youpin-city/youpin-web-admin#35]
- Set `is_archived` field to `true` (use PATCH to `/pins/<pinID>).
- An archived pin will not be listed in `issue` page.
- The archive page is similar to issue page but shows only archived pins.
- Archived pins don't affect stats in dashboard.

**Comment by rapee** [comment]
@supasate Should I call API like this?
- In issue page, `/pins?is_archive=false`
- In archive page, `/pins?is_archive=true`

**Comment by supasate** [comment]
Yes. (`is_archived` has `d` at the end)
