### ISSUE TITLE
Able to add more categories in settings

### ISSUE THREAD

**Issue by supasate** [youpin-city/youpin-web-admin#58]

**Comment by rapee** [comment]
Use following categories:

Order|Name|Code
---|---|---
1|แจ้งซ่อม | repair
2|บริการ | service
3|IT | it
4|เสนอแนะ | suggestion
5|ห้องเรียน | classroom
6|ปลอดภัย | safety
7|ความสะอาด | sanitary
8|จราจร | traffic
9|อื่น ๆ | others

**Comment by puripant** [comment]
A. Manoj suggested changing "ปลอดภัย" to "ความปลอดภัย" across the platform (bot, web)
